### PR TITLE
Add ExtractStrict and ExcludeStrict

### PR DESCRIPTION
**Pull request by ekilah**
Fixes https://github.com/pelotom/type-zoo/issues/37

I ran `yarn format` and picked up some changes in `public.ts` and in the `index.d.ts`. 

Let me know if I should also include a version number change, or if you do that yourself when publishing.

(First time using `dtslint`, any tips welcome. I tried to do e.g.`$ExpectType 'red' | 'green' | 'blue'` for `type PrimaryColors` and it threw errors saying it got `any` instead. maybe this type of thing doesn't work in `dtslint` or I was using it wrong? edit: maybe i could try the suggestions here: https://github.com/microsoft/dtslint/issues/179 if you want me to add more tests)

### CODE REVIEW

**Comment by ekilah** [comment]
I saw the CI errors locally too:

```
Error: /home/travis/build/pelotom/type-zoo/types/param-n.ts:11:1
ERROR: 11:1  expect  Expected type to be:
  {}
got:
  unknown
ERROR: 13:1  expect  Expected type to be:
  {}
got:
  unknown
ERROR: 43:1  expect  Expected type to be:
  {}
got:
  unknown
```

(unrelated to these changes)

**Comment by pelotom** [comment]
The CI errors are due to recent changes in TypeScript that make it so `unknown` is used as an upper bound instead of `{}` when a type parameter can't be inferred. So we should just switch the expectations to `unknown`.

**Comment by ekilah** [comment]
@pelotom seems to fail either way, using different TS versions?

**Comment by pelotom** [comment]
I pushed a fix to `master`. Basically we need to expect a minimum TypeScript version of 3.5 now.

**Comment by ekilah** [comment]
ah, there we go, thanks. lmk if the rest looks good when you have time!

**Comment by ekilah** [comment]
Removed. thought it'd be nice for people unfamiliar with what the difference is between `Pick` and `Extract`, but that's not really the job of this repo I guess.

**Comment by pelotom** [comment]
Thanks!

**Comment by ekilah** [comment]
what's your publishing schedule for `npm` btw?

**Comment by pelotom** [comment]
Just published.

**Pull request merged**
