### PR TITLE
Add OmitStrict type for when you don't want to be permissive.

### PR DESCRIPTION
**Pull request by seansfkelley**
I preferred the old behavior of `Omit` before it was made permissive, but I understand the use-cases for it. This PR re-introduces the original behavior under a different name.

The benefit that a stricter type has is primarily:

- Preventing typos.
- Allowing the compiler to pick up on rename refactors automatically.

Currently, permissive `Omit` acts as a "barrier" that prevents rename refactors from passing through, which means that any such refactor generates whole bunches of errors that have to be manually fixed. If the field in question is optional, this can actually introduce bugs.

I'm open to bike-shedding the name, but I'd like to have both types available so I don't have to pin to an old version of the library or re-declare my own strict variants!

### CODE REVIEW

**Comment by seansfkelley** [comment]
The build is failing for reasons unrelated to my changes. I see these failures locally as well, but I'm not sure how to fix them.

**Comment by seansfkelley** [comment]
Ping @pelotom, thoughts?

**Comment by seansfkelley** [comment]
🏓 @pelotom

**Comment by pelotom** [comment]
Seems reasonable; if you can make CI happy I'll merge.

**Comment by seansfkelley** [comment]
Perfect, thanks. However, the CI failures are caused by unrelated code from #24, perhaps something changed in 3.x that breaks it? Ping @fbartho, do you know what's up with `Param*` in 3.x?

**Comment by fbartho** [comment]
@seansfkelley I'm didn't end up using ParamTypes in my codebase (yet) due to a lag in getting dependencies updated. So I'm just now upgrading to TS 3.1!

Separately, there exists this ticket:
- https://github.com/pelotom/type-zoo/issues/26 that talks about the "right" way to do ParamTypes
- Also this PR: https://github.com/pelotom/type-zoo/pull/28 has some change related to it as well, but I haven't read the code yet.

I'll have time to look at ParamTypes in like a week or two, but if somebody could take a look at that issue & pr, and help us figure out the "right" fix, I certainly would be appreciative.

**Comment by seansfkelley** [comment]
Master is currently broken due to the code introduced in #24. I do not understand how it works or how to fix it, so I have not done so. @pelotom has not given me the okay to merge it anyway even though the code in this PR is passing tests.

**Comment by seansfkelley** [comment]
@pelotom looks like master fixed itself (new patch version of the language automatically pulled in?) so this PR now has passing builds. Could you take a look/merge/release it?

**Comment by seansfkelley** [comment]
Thank you!

**Comment by ekilah** [comment]
Just ran into this, thanks for bringing back the old functionality @seansfkelley .

@pelotom, why was the original behavior removed here? https://github.com/pelotom/type-zoo/commit/761eff95467889ee1c56c34beb42f61c1dfc76c0 Can't tell from the commit message.

**Comment by pelotom** [comment]
@ekilah it’s just a different use case, where you don’t want to have to check that the properties you’re omitting are actually defined on the source type (I’ve found this to be the most common use case in practice but YMMV). In retrospect though I shouldn’t have redefined `Omit` but instead introduced a new operator for the relaxed version.

**Comment by ekilah** [comment]
@pelotom 👍 agreed, but too late now 😛 

I will say that after doing a find/replace in my project, there was only one place where I actually wanted `Omit` and not `OmitStrict`, and I'm actually skeptical of that line of code now anyways. Getting the old behavior back even caught a couple refactoring mistakes. So, YMMV indeed!

**Pull request merged**
